name: Validate & publish (tag)

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@797f0b74bbfe4805e811338a4a2e3fe3e1326a8a

  pre-publish:
    needs: validate
    uses: ./.github/workflows/unbound-exporter-pre-publish.yml

  get-version:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.event-ref-version.outputs.VERSION }}
    steps:
      - name: Extract version from event ref
        id: event-ref-version
        run: echo "VERSION=$(echo ${REF_NAME#v})" >>$GITHUB_OUTPUT
        env:
          REF_NAME: ${{ github.ref_name }}

  publish:
    needs: [validate, pre-publish, get-version]
    permissions:
      packages: write
      id-token: write # used for sigstore/fulcio identity challenge
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@797f0b74bbfe4805e811338a4a2e3fe3e1326a8a
    with:
      dockerfile-dir: src
      dhub-readme-file: ./CONTAINER.md
      version: ${{ needs.get-version.outputs.version }}
      container-image-name: ${{ needs.pre-publish.outputs.container-image-name }}
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
