name: Validate & publish (branch)

on:
  push:
    branches: [ main ]

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@f500e7cdca8a754d7f78b7706fba2278ffc42f1b

  get-version:
    needs: validate
    uses: anthochamp/dev-toolbox/.github/workflows/util-get-latest-git-version-tag.yml@f500e7cdca8a754d7f78b7706fba2278ffc42f1b

  pre-publish:
    needs: validate
    uses: ./.github/workflows/unbound-exporter-pre-publish.yml

  publish:
    needs: [validate, get-version, pre-publish]
    permissions:
      packages: write
      id-token: write # used for sigstore/fulcio identity challenge
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@f500e7cdca8a754d7f78b7706fba2278ffc42f1b
    with:
      dockerfile-dir: src
      dhub-readme-file: ./CONTAINER.md
      version: ${{ needs.get-version.outputs.version }}
      container-image-name: ${{ needs.pre-publish.outputs.container-image-name }}
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
